[project]
name = "pg-region-debug"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "psycopg>=3.2.12",
    "psycopg-binary>=3.2.12",
    "psycopg2==2.9.9",
]
